server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres/dev_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.demo: DEBUG
    org.springframework.security: DEBUG
    org.thymeleaf: DEBUG